project:
  type: website
  output-dir: docs

website:
  title: "Davi A F silva"
  navbar:
    left:
      - href: curriculum.qmd
        text: CV
      - personal_projects.qmd

format:
  html:
    theme: Lux
    css: styles.css
    toc: true